// Mapa centralizado: ID de atividade → categoria Kids
// Cobre atividadesData.js + atividadesExtra.js
const map = {
  // ── NÚMEROS ────────────────────────────────────────
  exp_numeros_1_10:          'matematica',
  exp_numeros_animais:       'matematica',
  exp_numeros_frutas:        'matematica',
  con_numeros_11_20:         'matematica',
  con_numeros_dezenas:       'matematica',
  con_numeros_pares:         'matematica',
  cri_numeros_negativos:     'matematica',
  cri_numeros_romanos:       'matematica',
  inv_numeros_potencias:     'matematica',
  inv_numeros_fibonacci:     'matematica',

  // ── FORMAS / CORES / ALFABETO ─────────────────────
  exp_formas_2:              'formas_cores',
  exp_formas_alimentos:      'formas_cores',
  exp_formas_animais:        'formas_cores',
  exp_formas_brinquedos:     'formas_cores',
  exp_formas_espaco:         'formas_cores',
  exp_formas_casas:          'formas_cores',
  exp_formas_mar:            'formas_cores',
  exp_formas_frutas:         'formas_cores',
  exp_formas_corpo:          'formas_cores',
  con_formas_solidos:        'formas_cores',
  con_formas_poligonos:      'formas_cores',
  con_formas_angulos:        'formas_cores',
  con_formas_perimetro:      'formas_cores',
  con_formas_quadrilateros:  'formas_cores',
  con_formas_triangulos:     'formas_cores',
  con_formas_transformacoes: 'formas_cores',
  con_formas_arquitetura:    'formas_cores',
  con_formas_mapa:           'formas_cores',
  cri_formas_avancadas:      'formas_cores',
  cri_formas_simetria:       'formas_cores',
  cri_formas_arte:           'formas_cores',
  cri_formas_coordenadas:    'formas_cores',
  cri_formas_circulos:       'formas_cores',
  cri_formas_solidos3d:      'formas_cores',
  cri_formas_padroes:        'formas_cores',
  cri_formas_vetorial:       'formas_cores',
  cri_formas_tangram:        'formas_cores',
  inv_formas_fractais:       'formas_cores',
  inv_formas_topologia:      'formas_cores',
  inv_formas_4d:             'formas_cores',
  inv_formas_fibonacci:      'formas_cores',
  inv_formas_computacional:  'formas_cores',
  inv_formas_origami:        'formas_cores',
  inv_formas_nao_euclidiana: 'formas_cores',
  inv_formas_platao:         'formas_cores',
  inv_formas_knot:           'formas_cores',
  exp_formas_geometricas:    'formas_cores',
  exp_cores:                 'formas_cores',
  exp_alfabeto:              'formas_cores',
  con_formas_geometricas:    'formas_cores',
  con_cores:                 'formas_cores',
  con_alfabeto:              'formas_cores',
  cri_formas_geometricas:    'formas_cores',
  cri_cores:                 'formas_cores',
  cri_alfabeto:              'formas_cores',
  inv_formas_geometricas:    'formas_cores',
  inv_cores:                 'formas_cores',
  inv_alfabeto:              'formas_cores',

  // ── QUIZ ───────────────────────────────────────────
  exp_quiz_animais:          'animais',
  exp_quiz_animais2:         'animais',
  exp_quiz_formas:           'formas_cores',
  exp_quiz_frutas:           'frutas',
  exp_quiz_corpo:            'corpo_humano',
  con_quiz_corpo:            'corpo_humano',
  con_quiz_ciencias:         'planeta_terra',
  con_quiz_ciencias2:        'planeta_terra',
  con_quiz_matematica:       'matematica',
  con_quiz_matematica2:      'matematica',
  con_quiz_brasil:           'historia_brasil',
  cri_quiz_arte:             'arte',
  cri_quiz_ecologia:         'planeta_terra',
  cri_quiz_historia:         'historia_brasil',
  cri_quiz_ciencias2:        'planeta_terra',
  cri_quiz_geografia:        'planeta_terra',
  inv_quiz_logica:           'matematica',
  inv_quiz_tech:             'tecnologia',
  inv_quiz_programacao:      'tecnologia',
  inv_quiz_fisica:           'fisica',
  inv_quiz_filosofia:        'filosofia',
  inv_quiz_filosofia2:       'filosofia',

  // ── MEMÓRIA ────────────────────────────────────────
  exp_memoria_frutas:         'frutas',
  exp_memoria_fazenda:        'animais',
  con_memoria_animais_paises: 'animais',
  con_memoria_capitais:       'historia_brasil',
  con_memoria_paises:         'historia_brasil',
  con_memoria_habitats:       'planeta_terra',
  con_memoria_geometria:      'matematica',
  cri_memoria_inventores:     'tecnologia',
  cri_memoria_cientistas:     'fisica',
  cri_memoria_elementos:      'planeta_terra',
  cri_memoria_biomas:         'planeta_terra',
  inv_memoria_codigo:         'tecnologia',
  inv_memoria_linguagens:     'tecnologia',
  inv_memoria_linguagens_2:   'tecnologia',
  inv_memoria_estruturas:     'tecnologia',
  inv_memoria_cientistas:     'fisica',

  // ── MEMÓRIA (exploradores — sem categoria própria) ──
  exp_memoria_profissoes:     'profissoes',
  exp_memoria_transporte:     'transporte',

  // ── SEQUÊNCIA ──────────────────────────────────────
  exp_sequencia_cores:        'formas_cores',
  con_sequencia_numeros:      'matematica',
  con_sequencia_tabuada:      'matematica',
  cri_sequencia_logica:       'matematica',
  cri_sequencia_geometrica:   'matematica',
  inv_sequencia_algoritmo:    'tecnologia',
  inv_sequencia_cripto:       'tecnologia',
  exp_seq_formas:             'formas_cores',
  exp_seq_numeros2:           'matematica',
  exp_seq_bichinhos:          'animais',
  con_seq_dobros:             'matematica',
  con_seq_multiplos:          'matematica',
  con_seq_logica:             'matematica',
  cri_seq_progressoes:        'matematica',
  cri_seq_fracoes:            'matematica',
  cri_seq_mistas:             'matematica',
  inv_seq_complexidade:       'tecnologia',
  inv_seq_binario:            'tecnologia',
  inv_seq_avancado:           'tecnologia',

  // ── PADRÃO ────────────────────────────────────────
  exp_padrao:                 'matematica',
  con_padrao:                 'matematica',
  cri_padrao:                 'matematica',
  inv_padrao:                 'matematica',
  exp_padrao_cores:           'formas_cores',
  exp_padrao_numeros:         'matematica',
  exp_padrao_animais:         'animais',
  con_padrao_tabuada:         'matematica',
  con_padrao_logica:          'matematica',
  con_padrao_matematica:      'matematica',
  cri_padrao_progressoes:     'matematica',
  cri_padrao_logica_avancada: 'matematica',
  cri_padrao_ciencias:        'planeta_terra',
  inv_padrao_binario:         'tecnologia',
  inv_padrao_algoritmos:      'tecnologia',
  inv_padrao_matematica_avancada: 'matematica',

  // ── ROBÔ ──────────────────────────────────────────
  exp_robo:            'tecnologia',
  con_robo:            'tecnologia',
  cri_robo:            'tecnologia',
  inv_robo:            'tecnologia',
  exp_robo_passeio:    'tecnologia',
  exp_robo_jardim:     'tecnologia',
  con_robo_cidade:     'tecnologia',
  con_robo_fabrica:    'tecnologia',
  cri_robo_labirinto:  'tecnologia',
  cri_robo_circuito:   'tecnologia',
  inv_robo_algoritmo:  'tecnologia',
  inv_robo_otimizacao: 'tecnologia',

  // ── LABIRINTO ─────────────────────────────────────
  exp_labirinto:            'matematica',
  exp_labirinto_floresta:   'planeta_terra',
  exp_labirinto_castelo:    'historia_brasil',
  exp_labirinto_fazenda:    'animais',
  exp_labirinto_fundo_mar:  'golfinhos',
  con_labirinto:            'matematica',
  con_labirinto_escola:     'matematica',
  con_labirinto_piramide:   'historia_brasil',
  con_labirinto_espaco:     'planeta_terra',
  con_labirinto_caverna:    'planeta_terra',
  cri_labirinto:            'matematica',
  cri_labirinto_cyber:      'tecnologia',
  cri_labirinto_DNA:        'corpo_humano',
  cri_labirinto_oceano:     'golfinhos',
  cri_labirinto_computador: 'tecnologia',
  inv_labirinto:            'tecnologia',
  inv_labirinto_quantum:    'fisica',
  inv_labirinto_neural:     'tecnologia',
  inv_labirinto_blockchain: 'tecnologia',
  inv_labirinto_matrix:     'tecnologia',

  // ── QUIZ IA ───────────────────────────────────────
  exp_quizia:   'tecnologia',
  exp_quizia_2: 'tecnologia',
  exp_quizia_3: 'tecnologia',
  con_quizia:   'tecnologia',
  con_quizia_2: 'tecnologia',
  con_quizia_3: 'tecnologia',
  cri_quizia:   'tecnologia',
  cri_quizia_2: 'tecnologia',
  cri_quizia_3: 'tecnologia',
  inv_quizia:   'tecnologia',
  inv_quizia_2: 'tecnologia',
  inv_quizia_3: 'tecnologia',

  // ── ROBO fase4 ────────────────────────────────────
  exp_robo_4:              'tecnologia',
  exp_robo_5:              'tecnologia',
  con_robo_4:              'tecnologia',
  con_robo_5:              'tecnologia',
  cri_robo_3:              'tecnologia',
  cri_robo_4:              'tecnologia',
  inv_robo_3:              'tecnologia',
  inv_robo_4:              'tecnologia',

  // ── PADRÃO fase4 ──────────────────────────────────
  exp_padrao_clima:        'planeta_terra',
  exp_padrao_estacoes:     'planeta_terra',
  con_padrao_historia:     'historia_brasil',
  con_padrao_natureza:     'planeta_terra',
  cri_padrao_musica:       'arte',
  cri_padrao_tecnologia:   'tecnologia',
  inv_padrao_criptografia: 'tecnologia',
  inv_padrao_sistemas:     'tecnologia',

  // ── BLOCOS & INVENTOR ─────────────────────────────
  exp_blocos_1:  'tecnologia',
  exp_blocos_2:  'tecnologia',
  exp_blocos_3:  'tecnologia',
  exp_blocos_4:  'tecnologia',
  exp_robo_2:    'tecnologia',
  exp_robo_3:    'tecnologia',
  con_blocos:    'tecnologia',
  con_blocos_2:  'tecnologia',
  con_blocos_3:  'tecnologia',
  con_blocos_4:  'tecnologia',
  con_robo_2:    'tecnologia',
  con_robo_3:    'tecnologia',
  cri_blocos:    'tecnologia',
  cri_blocos_2:  'tecnologia',
  cri_blocos_3:  'tecnologia',
  cri_blocos_4:  'tecnologia',
  cri_robo_2:    'tecnologia',
  inv_blocos:    'tecnologia',
  inv_blocos_2:  'tecnologia',
  inv_blocos_3:  'tecnologia',
  inv_blocos_4:  'tecnologia',
  inv_robo_2:    'tecnologia',
  con_inventor:  'tecnologia',
  con_inventor_2:'tecnologia',
  con_inventor_3:'tecnologia',
  cri_inventor:  'tecnologia',
  cri_inventor_2:'tecnologia',
  cri_inventor_3:'tecnologia',
  inv_inventor:  'tecnologia',
  inv_inventor_2:'tecnologia',
  inv_inventor_3:'tecnologia',

  // ── FASE 5 — quiz e inventor ──────────────────
  exp_quiz_espaco:          'planeta_terra',
  exp_quiz_profissoes:      'profissoes',
  con_quiz_inventores:      'tecnologia',
  con_quiz_biomas:          'planeta_terra',
  cri_quiz_matematica:      'matematica',
  cri_quiz_mente:           'corpo_humano',
  inv_quiz_epistemologia:   'filosofia',
  inv_quiz_civilizacoes:    'historia_brasil',
  con_inventor_4:           'tecnologia',
  con_inventor_5:           'tecnologia',
  cri_inventor_4:           'tecnologia',
  cri_inventor_5:           'tecnologia',
  inv_inventor_4:           'tecnologia',
  inv_inventor_5:           'tecnologia',

  // ── INGLÊS ────────────────────────────────────────
  exp_ingles:                 'ingles',
  exp_ingles_corpo:           'ingles',
  exp_ingles_comida:          'ingles',
  exp_ingles_roupas:          'ingles',
  exp_ingles_casa:            'ingles',
  exp_ingles_tempo:           'ingles',
  exp_ingles_escola:          'ingles',
  exp_ingles_natureza:        'ingles',
  exp_ingles_familia:         'ingles',
  exp_ingles_acoes:           'ingles',
  con_ingles:                 'ingles',
  con_ingles_profissoes:      'ingles',
  con_ingles_viagem:          'ingles',
  con_ingles_esportes:        'ingles',
  con_ingles_tecnologia:      'ingles',
  con_ingles_sentimentos:     'ingles',
  con_ingles_natureza:        'ingles',
  con_ingles_lugares:         'ingles',
  con_ingles_compras:         'ingles',
  con_ingles_corpo:           'ingles',
  cri_ingles:                 'ingles',
  cri_ingles_passado:         'ingles',
  cri_ingles_futuro:          'ingles',
  cri_ingles_continuo:        'ingles',
  cri_ingles_adjetivos:       'ingles',
  cri_ingles_perguntas:       'ingles',
  cri_ingles_plurais:         'ingles',
  cri_ingles_comparativo:     'ingles',
  cri_ingles_preposicoes:     'ingles',
  cri_ingles_quantificadores: 'ingles',
  inv_ingles:                 'ingles',
  inv_ingles_ciencia:         'ingles',
  inv_ingles_historia:        'ingles',
  inv_ingles_tecnologia:      'ingles',
  inv_ingles_natureza:        'ingles',
  inv_ingles_cultura:         'ingles',
  inv_ingles_economia:        'ingles',
  inv_ingles_saude:           'ingles',
  inv_ingles_matematica:      'ingles',
  inv_ingles_filosofia:       'ingles',

  // ── NÚMEROS extra (Step 2 original) ──────────────
  exp_numeros_animais:         'matematica',
  exp_numeros_frutas:          'matematica',
  con_numeros_11_20:           'matematica',
  con_numeros_dezenas:         'matematica',
  con_numeros_pares:           'matematica',
  cri_numeros_negativos:       'matematica',
  cri_numeros_romanos:         'matematica',
  inv_numeros_potencias:       'matematica',
  inv_numeros_fibonacci:       'matematica',

  // ── NÚMEROS extra (expansão 10/faixa) ────────────
  exp_numeros_planetas:        'matematica',
  exp_numeros_flores:          'matematica',
  exp_numeros_estrelas:        'matematica',
  exp_numeros_brinquedos:      'matematica',
  exp_numeros_instrumentos:    'matematica',
  exp_numeros_cores:           'matematica',
  exp_numeros_natureza2:       'matematica',
  con_numeros_impares:         'matematica',
  con_numeros_multiplos3:      'matematica',
  con_numeros_multiplos5:      'matematica',
  con_numeros_multiplos4:      'matematica',
  con_numeros_centenas:        'matematica',
  con_numeros_geometria:       'matematica',
  con_numeros_calendario:      'matematica',
  cri_numeros_quadrados:       'matematica',
  cri_numeros_primos:          'matematica',
  cri_numeros_fracoes:         'matematica',
  cri_numeros_binario:         'matematica',
  cri_numeros_famosos:         'matematica',
  cri_numeros_temperatura:     'matematica',
  cri_numeros_angulos:         'matematica',
  inv_numeros_constantes:      'matematica',
  inv_numeros_bases:           'matematica',
  inv_numeros_grandes:         'matematica',
  inv_numeros_fisica:          'matematica',
  inv_numeros_astronomia:      'matematica',
  inv_numeros_probabilidade:   'matematica',
  inv_numeros_logaritmos:      'matematica',

  // ── CORES extra (Step 4 original) ────────────────
  exp_cores_arcoiris:          'formas_cores',
  exp_cores_natureza:          'formas_cores',
  con_cores_primarias:         'formas_cores',
  con_cores_temperaturas:      'formas_cores',
  cri_cores_circulo:           'formas_cores',
  inv_cores_espectro:          'formas_cores',

  // ── CORES extra (expansão 10/faixa) ──────────────
  exp_cores_brinquedos:        'formas_cores',
  exp_cores_alimentos:         'formas_cores',
  exp_cores_bichinhos:         'formas_cores',
  exp_cores_fazenda:           'formas_cores',
  exp_cores_ceu:               'formas_cores',
  exp_cores_sentimentos:       'formas_cores',
  exp_cores_frutas:            'formas_cores',
  con_cores_emocoes:           'formas_cores',
  con_cores_estacoes:          'formas_cores',
  con_cores_bandeiras:         'formas_cores',
  con_cores_arte:              'formas_cores',
  con_cores_materiais:         'formas_cores',
  con_cores_mistura:           'formas_cores',
  con_cores_sombra_luz:        'formas_cores',
  cri_cores_aditiva:           'formas_cores',
  cri_cores_subtrativa:        'formas_cores',
  cri_cores_harmonia_comp:     'formas_cores',
  cri_cores_harmonia_anal:     'formas_cores',
  cri_cores_psicologia:        'formas_cores',
  cri_cores_simbolismo:        'formas_cores',
  cri_cores_impressionismo:    'formas_cores',
  cri_cores_optica:            'formas_cores',
  inv_cores_percep:            'formas_cores',
  inv_cores_quimica_pig:       'formas_cores',
  inv_cores_astro:             'formas_cores',
  inv_cores_biolum:            'formas_cores',
  inv_cores_uv_ir:             'formas_cores',
  inv_cores_computacao:        'formas_cores',
  inv_cores_metameria:         'formas_cores',

  // ── ALFABETO extra ────────────────────────────────
  exp_alfabeto_animais:        'formas_cores',
  exp_alfabeto_comida:         'formas_cores',
  exp_alfabeto_flores:         'formas_cores',
  exp_alfabeto_oceano:         'formas_cores',
  exp_alfabeto_esportes:       'formas_cores',
  exp_alfabeto_frutas:         'formas_cores',
  exp_alfabeto_brinquedos:     'formas_cores',
  exp_alfabeto_lugares:        'formas_cores',
  exp_alfabeto_dinos:          'formas_cores',
  con_alfabeto_profissoes:     'formas_cores',
  con_alfabeto_natureza:       'formas_cores',
  con_alfabeto_corpo:          'formas_cores',
  con_alfabeto_paises:         'formas_cores',
  con_alfabeto_inventos:       'formas_cores',
  con_alfabeto_mitologia:      'formas_cores',
  con_alfabeto_culinaria:      'formas_cores',
  con_alfabeto_folclore:       'formas_cores',
  con_alfabeto_cidades:        'formas_cores',
  cri_alfabeto_ciencias:       'formas_cores',
  cri_alfabeto_filosofia:      'formas_cores',
  cri_alfabeto_arte:           'formas_cores',
  cri_alfabeto_historia:       'formas_cores',
  cri_alfabeto_literatura:     'formas_cores',
  cri_alfabeto_matematica:     'formas_cores',
  cri_alfabeto_geopolitica:    'formas_cores',
  cri_alfabeto_biologia_av:    'formas_cores',
  cri_alfabeto_psicologia:     'formas_cores',
  inv_alfabeto_tecnologia:     'formas_cores',
  inv_alfabeto_fisica:         'formas_cores',
  inv_alfabeto_filosofia_av:   'formas_cores',
  inv_alfabeto_economia:       'formas_cores',
  inv_alfabeto_linguistica:    'formas_cores',
  inv_alfabeto_astronomia:     'formas_cores',
  inv_alfabeto_quimica:        'formas_cores',
  inv_alfabeto_politica:       'formas_cores',
  inv_alfabeto_medicina:       'formas_cores',

  // ── COLORIR ────────────────────────────────────────
  exp_memoria_profissoes_2:    'profissoes',
  cri_memoria_inventores_2:    'tecnologia',
  exp_musica_sons:             'arte',
  exp_musica_rapido_lento:     'arte',
  exp_musica_eco:              'arte',
  con_musica_notas:            'arte',
  con_musica_ritmo:            'arte',
  con_musica_instrumentos:     'arte',
  cri_musica_pauta:            'arte',
  cri_musica_figuras:          'arte',
  cri_musica_escala:           'arte',
  inv_musica_intervalos:       'arte',
  inv_musica_tonalidade:       'arte',
  inv_musica_fisica:           'arte',
  exp_colorir_sol:             'formas_cores',
  exp_colorir_sorvete:         'formas_cores',
  exp_colorir_balao:           'formas_cores',
  exp_colorir_bolo:            'formas_cores',
  exp_colorir_gato:            'formas_cores',
  con_colorir_coruja:          'formas_cores',
  con_colorir_trem:            'formas_cores',
  con_colorir_veleiro:         'formas_cores',
  con_colorir_pipa:            'formas_cores',
  cri_colorir_castelo:         'formas_cores',
  cri_colorir_dinossauro:      'formas_cores',
  cri_colorir_praia:           'formas_cores',
  cri_colorir_pinguim:         'formas_cores',
  inv_colorir_mandala:         'formas_cores',
  inv_colorir_vitral:          'formas_cores',
  inv_colorir_celula:          'formas_cores',
  inv_colorir_montanhas:       'formas_cores',
  exp_colorir_casa:            'formas_cores',
  exp_colorir_flor:            'formas_cores',
  con_colorir_peixe:           'formas_cores',
  con_colorir_foguete:         'formas_cores',
  con_colorir_borboleta:       'formas_cores',
  cri_colorir_robo:            'formas_cores',
  cri_colorir_arvore:          'formas_cores',
  cri_colorir_carro:           'formas_cores',
  inv_colorir_cidade:          'formas_cores',
  inv_colorir_sistema_solar:   'formas_cores',
  inv_colorir_ponte:           'formas_cores',

  // ── SÍLABAS ────────────────────────────────────────
  exp_silabas:                 'formas_cores',
  con_silabas:                 'formas_cores',

  // ── QUIZ — expansão de 08/08/2026 (30 novos, fecha 15 por faixa) ──────
  exp_quiz_transportes:        'transporte',
  exp_quiz_casa:               'tecnologia',
  exp_quiz_tempo:              'planeta_terra',
  exp_quiz_bichinhos:          'animais',
  exp_quiz_comida:             'frutas',
  exp_quiz_higiene:            'corpo_humano',
  exp_quiz_oceano:             'golfinhos',
  exp_quiz_sons:               'arte',

  con_quiz_espaco:             'planeta_terra',
  con_quiz_dinossauros:        'dinossauros',
  con_quiz_agua:               'planeta_terra',
  con_quiz_oceanos:            'golfinhos',
  con_quiz_energia:            'fisica',
  con_quiz_portugues:          'arte',
  con_quiz_reciclagem:         'planeta_terra',

  cri_quiz_corpo:              'corpo_humano',
  cri_quiz_astronomia:         'planeta_terra',
  cri_quiz_tecnologia:         'tecnologia',
  cri_quiz_dinheiro:           'matematica',
  cri_quiz_musica:             'arte',
  cri_quiz_esportes:           'esportes',
  cri_quiz_literatura:         'arte',
  cri_quiz_clima:              'planeta_terra',

  inv_quiz_genetica:           'corpo_humano',
  inv_quiz_ia:                 'tecnologia',
  inv_quiz_seguranca:          'tecnologia',
  inv_quiz_economia:           'matematica',
  inv_quiz_quimica:            'fisica',
  inv_quiz_estatistica:        'matematica',
  inv_quiz_evolucao:           'animais',
}

export function getKidsLink(atividadeId) {
  return map[atividadeId] ?? null
}
